### ISSUE TITLE
test against clvm/tests cases

### ISSUE THREAD

**Issue by arvidn** [Chia-Mine/clvm-js#30]
There are a lot of useful test cases in the [clvm](https://github.com/Chia-Network/clvm) repository.

Specifically the `.txt` files in:

https://github.com/Chia-Network/clvm/tree/main/tests/brun
https://github.com/Chia-Network/clvm/tree/main/tests/edge-cases
https://github.com/Chia-Network/clvm/tree/main/tests/unknown-op

They are in the form of a `brun` command line followed by the expected output. In order to run them, I suppose you may need to parse the `brun` command line options and set up your environment accordingly.

These tests ensure that the cost does not regress for instance.

**Comment by ChiaMineJP** [comment]
I actually forgot to think what is the best way to handle those tests.
At first grance, I feel those tests should not be included in `clvm` repository, because to run those test it requires clvm_tools, which depends on clvm itself. Then it creates circular dependency!

In my opinion, those tests should be in clvm_tools repository.
How do you think about this?
Should I ignore this circular dependency for the tests? Or should I run those tests in `clvm_tools-js` repository?

**Comment by ChiaMineJP** [comment]
I created tests in  [clvm_tools-js repository](https://github.com/Chia-Mine/clvm_tools-js/tree/main/tests) as I wrote above.

https://github.com/Chia-Mine/clvm_tools-js/tree/main/tests/brun
https://github.com/Chia-Mine/clvm_tools-js/tree/main/tests/edge-cases
https://github.com/Chia-Mine/clvm_tools-js/tree/main/tests/unknown-op

[clvm_tools@0.9.2](https://github.com/Chia-Mine/clvm_tools-js) passed all the test!

**Comment by arvidn** [comment]
I agree with this not being a great setup, because of the circular dependency. However, the tests primarily exercises the clvm implementation, so I would think they belong in `clvm`. I think the main reason they depend on `clvm_tools` is because `clvm` itself doesn't contain a parser for the human readable source code.

However, we run these tests in `clvm_rs` as well, so the tests should *probably* live in an independent repository, used to ensure all implementations are in agreement.
